### ISSUE TITLE
Current hub release has corrupted layers

### ISSUE THREAD

**Issue by EugenMayer** [gocd/docker-gocd-agent-alpine-3.6#1]
I cannot pull not run the current latest release, it seems to be completely corrupted

**Comment by varshavaradarajan** [comment]
Verified that I can pull the image and run jobs on it just fine. Closing this. Please reopen it if you find that it is an issue with the image itself and provide specific details about it. :)

**Comment by varshavaradarajan** [comment]
Oh, for any issue regarding the agent docker images, please raise an issue on https://github.com/gocd/docker-gocd-agent. That's the repo we use to build all agents images. So, if you do find any issue, it may be that all agent images are affected.
